FROM python


WORKDIR /code
COPY requirements.txt /code/requirements.txt
RUN python -m pip install --upgrade pip

RUN pip install --no-cache-dir --no-dependencies -r requirements.txt

COPY . /code/

EXPOSE 8000

CMD ["fastapi", "run", "main.py", "--port", "8000", "--reload"]

#build "docker build -t backendsudoku .